# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FastdaimaResearch',
                'doc_host': 'https://fastdaima.github.io',
                'git_url': 'https://github.com/fastdaima/FastdaimaResearch',
                'lib_path': 'FastdaimaResearch'},
  'syms': {'FastdaimaResearch.core': {'FastdaimaResearch.core.foo': ('core.html#foo', 'FastdaimaResearch/core.py')}}}
